### ISSUE TITLE
andorid app

### ISSUE THREAD

**Issue by ftoledo** [rickparrish/fTelnet#25]
hi!!..

I have a android apk for ftelnet.. i can remember exactly when i instaled.. i think that few year ago..
now, I cannot find the app at andorid store.
 
Can you help me provide a download link for that apk?. Some friends want to connect to my bbs via android. 

thanks!!!

**Comment by rickparrish** [comment]
Sorry, I believe it was de-listed from the app stores months/years ago because I didn't update to the newer API versions.
