### ISSUE TITLE
Support for Atari/ATASCII broken

### ISSUE THREAD

**Issue by iommi1** [rickparrish/fTelnet#26]
I found that Atari/ATASCII was broken . I would do a pull request on this but really don't know how.(yet)

these are the options I used:

    Options.Emulation = 'Atari';
    Options.Enter = '\x9B';    
    Options.Font = 'Atari-Graphics_16x16';

this is the two code changes I needed to make

```
    }
            if (this._Options.Emulation === 'C64') {
                this._Options.Font = 'C64-Lower';
                this._Options.ScreenColumns = 40;
            }
            else if ((this._Options.Emulation === 'RIP') && (typeof RIP !== 'undefined')) {
                this._Options.Font = 'RIP_8x8';
                this._Options.ScreenRows = 43;
            }
            // added for atari**
                 else if (this._Options.Emulation === 'Atari')
            {
                this._Options.ScreenColumns = 40;
            }
           // end added for atari**
            else {
                this._Options.Emulation = 'ansi-bbs';
            }
            this.LoadProxySettings();
        }

 this._Crt.onscreensizechange.on(function () { _this.OnCrtScreenSizeChanged(); });
        this._Crt.BareLFtoCRLF = this._Options.BareLFtoCRLF;
        this._Crt.C64 = (this._Options.Emulation === 'C64');
            // added for atari
        this._Crt.Atari = (this._Options.Emulation === 'Atari');
           // end added for atari
        this._Crt.LocalEcho = this._Options.LocalEcho;
```

Hope this help the team to do a proper change  on this, this is an amazing tool

if you need to test this, try my bbs at  https://atari.electric-estates.com

**Comment by rickparrish** [comment]
Thanks, I've just incorporated your changes into fTelnet, and updated the embed wizard to include Atari in the emulation drop down.  I connected to your BBS and the new user message looked good to me, so hopefully that means it's working correctly!
