### ISSUE TITLE
C64 emulation not working

### ISSUE THREAD

**Issue by kcasteels** [rickparrish/fTelnet#5]
When I set the emulation type to "C64" the terminal is still in ANSI mode.  Using the iFrame code on the website does work in C64 mode though.  Is there a difference between the code?  I'm using the files in fTelnet/release

**Comment by kcasteels** [comment]
Hi again, is there any possibility of getting PETSCII support again with the latest version of the term?  Thanks!

**Comment by rickparrish** [comment]
C64 is something I had working in the older Flash-based client, but not all the code has been ported over to the HTML5 version.  If you're still interested it's something I could look into finishing.
