### ISSUE TITLE
 unknown SOCKS version?

### ISSUE THREAD

**Issue by meluvalli** [rickparrish/fTelnet#7]
Tried to run with my current SOCKS proxy (Danted).

When it hits the proxy server, proxy server returns:  unknown SOCKS version 71 in client request.

Any thoughts on what could be wrong?
Also tried using CCProxy for Windows, and it doesn't work with this proxy either.

Any recommendations on Linux Proxy server software?

**Comment by rickparrish** [comment]
fTelnet needs a specific type of proxy, so I doubt a standard SOCKS proxy will work unfortunately.
