### ISSUE TITLE
Should ymodem transfers be working?

### ISSUE THREAD

**Issue by tonytoon** [rickparrish/fTelnet#9]
I updated my Synchronet BBS to use the latest release of fTelnet, and I can't get ymodem-g to work. Are those still a WIP or might I have an issue on my end?

**Comment by rickparrish** [comment]
Synchronet was the software I tested with, so at one time YModem-G definitely worked with it.  I haven't tested transfers in a long time though so it's possible something changed.

Which proxy are you using?  That was always the most likely to cause transfer problems in the past.

**Comment by zharvek** [comment]
I did some testing and found ymodem to be broken for me in the latest release. I went back to version #7193f975786ebdc4198bc2124df0fff938c7a654 which is labeled as "Add ability to force wss:// connections". This version works for me using ymodem downloads. I have not yet gotten a newer version and tried to find the exact commit that brok ymodem.

**Comment by zharvek** [comment]
I did some work, 9da17a641f44fbe24dd4ca15a805266ef18cbc0f is the commit that broke it from my tests. This looks like it modified the byte stuff. The commit files exactly before this work great for ymodem downloads.

**Comment by rickparrish** [comment]
Thanks for tracking that down.  Looks like I flipped it when working on getting RIP icons loading.  I've reverted the change so hopefully that'll fix the ymodem transfer problems.

**Comment by zharvek** [comment]
@rickparrish Very nice. All my systems that use Y-Modem over fTelnet are working great. Thanks for the quick fix!

**Comment by rickparrish** [comment]
Perfect, I'm glad that did it.  I don't think I'll ever get around to working on RIP again, so no need to worry about the fact that icon loading is probably broken now :)

**Comment by opicron** [comment]
I still have issues with ymodem-g. I tried uploading files with native MysticBBS Ymodem, the result I get is:

Expected (N)ACK got 24

When using SEXYZ Ymodem-G the transfer stalls at 100%.

Could you try to upload a file by one of these protocols on bbs.theforze.eu with ftelnet?

Or use the http url, bbs.theforze.eu. Thank you in advance!
